vedmack/yadcf

lab/jquery.dataTables.yadcf.js
Adding space to the HTML markup of filter clear button id and onclick handler. It's good that I had to revisit this because I've found another spot besides the earlier 3: in that case single quotes are used when constructing the markup instead of double quotes, it's the first change.
=> Adding space between clear button id and onclick handler

jquery.dataTables.yadcf.js
This could be undesirable to anyone depending on it working as it did, but it doesn't seem like it's documented to ignore sorting when using multi_select_custom_func.
There could be other places that need this, but this change seemed to work for my usecase at least.
=> Honor sort_as with multi_select_custom_func

jquery.dataTables.yadcf.js
Made code global for initializing and refreshing the plugin.
Little confusion in line 691, for checking for "choose" you are using "getOptions(oTable.selector)[column_number].select_type"? Is this intentional or you can get same values multiple ways.
User just need to set initialize and refresh method for their plugin.
=> Added functionality to use any Select plugin for search

bower.json
I need to use your library in a proyect using webjars and when I tried to add it to http://www.webjars.org/bower it fails because bower.json doesn't contain the license information: "The bower.json file should specify the license. This will have to be fixed upstream."
Thanks
=> Added license information to bower.json so that it can be deployed to webjars.org repository

jquery.dataTables.yadcf.js
You can now define the values of placeholders in the different type of elements for filtering.
Usage :
```
yadcf.init(table, col_opts, {
lang: {
'select': 'Choisissez une valeur',
'filter': 'Tapez pour filtrer',
'range': ['De', 'à'],
'date': 'Choisissez une date'
}
});
```
I don't know if it will work with the $().dataTable().yadcf() init, I don't use older version of dataTable :wink:
=> Add lang option

jquery.dataTables.yadcf.js
It is was possible to customise the inputs via `style_class`, it is now possible to also customise the associated buttons.
Example with bootstrap
```js
style_class: 'custom-select',
style_button_class: 'btn btn-outline-primary'
```
=> Add style_button_class prop to customise buttons

jquery.dataTables.yadcf.js
In jQuery 3+, within yadcf.init() the DataTables instance, referenced by the local instance variable, doesn't have a selector property. It is undefined.
Recreating the selector property and setting it to the local tableSelector variable allows yadcf to be jQuery 3+ compatable.
Tested with jQuery 3.1.0
=> jQuery 3+ compatablility: Set instance.selector

jquery.dataTables.yadcf.js
I'm using webpack and without this I'm not able to do 
var table = $('#dtTable').DataTable(...);
yadcf.init(table , [{column_number : 0}]);
because yadcf is not available.
I've followed [this guide](http://ifandelse.com/its-not-hard-making-your-library-support-amd-and-commonjs/).
Ps: I've not tested this in a simple browser environment but it should works.
**Update**: there is a problem, inline codes like `onclick="yadcf.stopPropagation(event);"` can't works without the global `yadcf` variable.
=> Added support to AMD and CommonJS

src/jquery.dataTables.yadcf.js
This solves the case, when in SPA there might be tables with same selector on different SPA views and yadcf keeps the `plugins` object populated across these views, which can lead to DT mData errors.
#449
=> Remove a table reference in a `plugins` object upon dt destroy

src/jquery.dataTables.yadcf.js
When we set option like below (Using select2 with filter_container_id)
```
{ 
column_number: 7,
select_type: 'select2',
filter_container_id: 'badge-wise-search',
}
```
On each filter change its adding up multiple select boxes under the same filter. 
Eg:
=> Fix mutiple select box issue for select2 option

src/jquery.dataTables.yadcf.js
fix for #554 bug/feature 
jsfiddle: http://jsfiddle.net/qjpws9L7/1/ 
yadcf  now filters same as dt (search input top right corner)
=> added dt rendering into range number filters

src/jquery.dataTables.yadcf.js
if we use data prop when we initialize yadcf select filters ( e.g. ajax loaded table data), and later we add new records dropdown is missing new records,  Added external function which updates select filter with new data.
jsfiddle: http://jsfiddle.net/rmahnwce/
=> update select filters dropdown with new data

src/jquery.dataTables.yadcf.js
This is an obvious "fix" for my case of #614 and my app and the testcafe tests work.
I don't know why oLoadedState is null here, why the legacy api is apparently used and there are lots of other things I don't know.
=> Workaround for #614

jquery.dataTables.yadcf.js
Fixes https://github.com/vedmack/yadcf/issues/629, improves overall security and robustness, and readability too.
I didn't test it thoroughly, but the bundled example works properly.
Note that while many places prone to XSS are now safe, there are still places which look dangerous. For example:
https://github.com/m417z/yadcf/blob/cd4bf396bc7cc46aa0f7456d5ab0775ad9a94525/jquery.dataTables.yadcf.js#L1559
If the string which is part of the expression is untrusted, it must be escaped.
This pull request took more time than I expected, I'd appreciate if it gets merged.
Thanks for the library.
=> Use proper jQuery objects instead of strings for better security

src/jquery.dataTables.yadcf.js
Adds support for values like:
`A"B'C&nbsp;<script>alert(1)</script>`.
This is similar to this commit which was reverted:
https://github.com/vedmack/yadcf/pull/630/commits/a88cd9bf6206c8bac53e72bb1cd3e56a23e781ee
=> Properly support values with special characters

src/jquery.dataTables.yadcf.js
It's not supported at the moment, here's an example (first column):
https://jsfiddle.net/a4xkcbvs/
=> Support text_data_delimiter in exact match mode

src/jquery.dataTables.yadcf.js
This should fix the following issues. 
* https://github.com/vedmack/yadcf/issues/644
* https://github.com/vedmack/yadcf/issues/645
Note for #644, I considered moving the filter clear `$('#yadcf-filter-' + table_selector_jq_friendly + '-' + column_number).val('').removeClass("inuse");` above the modified if/else clause, but was worried about unintended side-effects.
Working example: https://jsbin.com/tanogon/edit?html,js,output
=> support date_custom_func exFilterColumn, clear

src/jquery.dataTables.yadcf.js
This makes this part of the function follow the same syntax order of class manipulation before table manipulation, as well as corrects a bug if someone is using DataTable.on('search') for custom page scripting based on filtered columns.
=> Fix Order of lines 1193/1194 Bug#656

src/jquery.dataTables.yadcf.js
This fixes a single char typo:
'number_slide' to 'number_slider'
=> correct typo in comment

src/jquery.dataTables.yadcf.js
This is a fix for issue #373 which causes significant issues for sites requiring strict CSP settings, allowing use of a `nonce` in the calling script tag, which which means the attached event handlers become trusted.
I have made a start as a proof of concept and on the fields/use cases that address our needs at DemandLogic. If @vedmack approves this approach, it could be refactored to match throughout. 
**UPDATE:** [JSFiddle](https://jsfiddle.net/dlstevepike/etLjacxd/15/)
=> Use dynamic event handlers on elements to prevent nonce-based CSP errors (unsafe-inline disallowed)
