beta/jquery.dataTables.yadcf.js
=> add filter_match_mode regex

README.md, example-bootstrap-datepicker.html, example-datepicker.html, jquery.dataTables.yadcf.js
In my project I don't use jQueryUI datepicker, instead of this plugin I use [Bootstrap Datepicker](https://github.com/Eonasdan/bootstrap-datetimepicker).
In example-bootstrap-datepicker.html I include some libraries (bootstrap datepicker, momentjs, jquery), don't look at file locations, this is only my quick example.
Maybe this changes can be useful for someone.
=> Possible to use jQueryUI datepicker or Bootstrap Datepicker

jquery.dataTables.yadcf.js
seems to work for me, but I'd like you just to review to make sure i'm not missing anything. I tested with select to as select_type as well but I do no have chosen in my environment.
There may be some nuances I don't understand here so please do review.
Thanks as always,
\- Mike
=> Fix issue #279 - clear css class on select when using custom_func

jquery.dataTables.yadcf.js
Do not escape regex special characters in this case.
Fixes #338
=> fix for multi_select w/ filter_match_mode "regex"

jquery.dataTables.yadcf.js
PR #358 again after rebasing and removing conflicts.
=> Resets minDate and maxDate from jquery-ui datepickers when clearing date range filter (rebased)

src/jquery.dataTables.yadcf.js
Issue here : https://github.com/vedmack/yadcf/issues/413
Thank you!
=> Add CSS class on DateRange fields

src/jquery.dataTables.yadcf.js
Fix https://github.com/vedmack/yadcf/issues/446
=> Allow to inject JQuery object like DataTable do 

src/jquery.dataTables.yadcf.js
=> Set the state preselected value only if the option exists in the select dropdown.

jquery.dataTables.yadcf.css, src/jquery.dataTables.yadcf.js
added requested feature #495 
jsfiddle with example : http://jsfiddle.net/6g5dkny7/10/
ADD-ON to this PR :
In my current project I have a request, to be able to visually distinguish text input, if regex or exclude checkbox is checked (e.g. different background color). So I also added this little feature, which adds css class ` .inuse-regex ` and ` .inuse-exclude ` to the text input, if the checkbox is checked.
=> PR feature #495

jquery.dataTables.yadcf.js, src/jquery.dataTables.yadcf.js
jsfiddle http://jsfiddle.net/6g5dkny7/11/
=> PR for bug #497

src/jquery.dataTables.yadcf.js
=> Fix for #501

src/jquery.dataTables.yadcf.js
js fiddle: http://jsfiddle.net/orps6c7n/ 
see request in network tab of developer tools
=> PR for feature reqest #527

src/jquery.dataTables.yadcf.js
jsfiddle: http://jsfiddle.net/wLztxabo/
=> fix for #545

src/jquery.dataTables.yadcf.js
jsFiddle: http://jsfiddle.net/yptwbonf/1/
=> PR for feature #546

src/jquery.dataTables.yadcf.js
jsFiddle:  http://jsfiddle.net/y0aqf98e/1/
=> PR for bug #550

src/jquery.dataTables.yadcf.js
working fiddle: http://jsfiddle.net/hrfwz8a1/
=> Fix bug#560

src/jquery.dataTables.yadcf.js
jsfiddle: http://jsfiddle.net/hLon4x25/
=> fix for #563 - Number filter not filtering by zero value

ISSUE_TEMPLATE.md, README.md, contributing.md, src/jquery.dataTables.yadcf.js
* docs for column_selector
* changed tabs to spaces in doc comments
* some minor typo fixes
=> docs: cleanup and column_selector

.gitignore, src/test/package.json, src/test/specs/test.html, src/test/specs/yadcf-test.js, src/test/wdio.conf.js
Hi @vedmack , finally had time to write some tests, initially I wanted to write just some unit test, but this would require more rewriting of the lib. So I come up with selenium webdriverIO automated tests.
For now there are just few basic test for filters, that I use in my app, but we can easilly add some more in a future if you like.
Usage:
1. run `npm install` within `/src/test` folder
2. (if 4 fails ) run` ./node_modules/.bin/selenium-standalone install` within the folder
3. replace test.html path with the real one in yadcf-test.js.
4. run  `./node_modules/.bin/wdio wdio.conf.js` within the folder
=> webdriverIO tests

src/jquery.dataTables.yadcf.js
Usage:
```js
yadcf.setDefaults({
language: {
'filter': 'Escribe para filtrar',
}
});
```
=> Resolves #610

jquery.dataTables.yadcf.js
Reverts vedmack/yadcf#630 it was applied to stable 0.9.3 instead of yadcf/src/ latest beta 😭
=> Revert "Use proper jQuery objects instead of strings for better security"

src/jquery.dataTables.yadcf.js, src/test/specs/test.html
A rebase of https://github.com/vedmack/yadcf/pull/630
=> Use proper jQuery objects instead of strings for better security (second try)

.gitignore, src/jquery.dataTables.yadcf.css, src/jquery.dataTables.yadcf.js
The first commit is larger, but it contains only whitespace changes.
=> Formatting, minor code fixes and typos

src/jquery.dataTables.yadcf.css
=> fix broken rendering of bootstrap-datetimepicker

src/jquery.dataTables.yadcf.js
I noticed some minor copy fixes in the docs.
=> minor copy fixes
